version: 0.1
log:
  fields:
    service: registry
storage:
  s3:
    region: ${AWS_REGION}
    bucket: ${AWS_BUCKET}
    accesskey: ${AWS_ACCESS_KEY_ID}
    secretkey: ${AWS_SECRET_ACCESS_KEY}
http:
  addr: :5000

