version: '3.8'

services:
  simpleweb1:
    image: localhost:5000/simple-web
    container_name: simpleweb1
    expose:
      - "80"

  simpleweb2:
    image: localhost:5000/simple-web
    container_name: simpleweb2
    expose:
      - "80"

  nginx:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - "8082:80"  # External port for load balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - simpleweb1
      - simpleweb2

